### ISSUE TITLE
FEATURE: Support parallel and for-each stage

### ISSUE THREAD

**Issue by korawica** [ddeutils/ddeutil-workflow#28]
From community discussion, we can enhance parallel stage by the below syntax:

```yaml
  stages:
    - run: echo "Sequential step"

    - name: Parallel stage
      parallel: 
        branch_id_1:
          stages:
            - run: echo "branch 1 sequential step 1"
            - run: echo "branch 1 sequential step 2"

        branch_id_2:
          stages:
            - run: echo "branch 2 sequential step 1"
            - run: echo "branch 2 sequential step 2"

    - run: echo "More sequential steps after the whole parallel part is done."
```

For for-each stage:

```yaml
  stages:
    - run: echo "Sequential step"

    - name: For-each stage
      foreach: ${{ params.arrays }}
      stages:
        - run: echo "foreach ${{ item }} sequential step 1"
        - run: echo "foreach ${{ item }} sequential step 2"

    - run: echo "More sequential steps after the whole parallel part is done."
```
