### ISSUE TITLE
[FEATURE]: Support trigger rules

### ISSUE THREAD

**Issue by korawica** [ddeutils/ddeutil-workflow#32]
### Operating System

Other

### Example Code

Support trigger rules for job or stage model objects.

### Description

For job,

```yaml
jobs:
  - first-job:
      stages:
        - name: "Demo"
          echo: "DEMO"
  - second-job:
      trigger-rule: all_complete
      stages:
        - name: "All complele"
          echo: "ALL COMPLELE"
```

For stage, the trigger rule will be used instead of the condition:

```yaml
- name: "Demo use condition"
  if: "${{ stages.<above-stage-id>.errors? }} is None"
  echo: "This will run if above stage error"
```

Replace by:

```yaml
- name: "Demo use condition"
  trigger-rule: all_complete
  echo: "This will run if above stage error"
```

But this stage always does not run because the core code raises an error when it has any error.

### Workflow Version

0.0.38
